# Generated by Django 3.0.9 on 2020-08-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20200815_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.TextField(),
        ),
    ]
