# Generated by Django 3.0.9 on 2020-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20200828_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
