# Generated by Django 3.0.9 on 2020-09-01 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20200828_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=64)),
                ('fecha_R', models.DateField(default=datetime.datetime.now)),
                ('tipo_usuario', models.CharField(default='cliente', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_Nac', models.DateField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario')),
            ],
        ),
    ]
