# Generated by Django 3.0.9 on 2020-08-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('logo', models.BinaryField()),
                ('razon_social', models.CharField(max_length=300)),
                ('ruc_cedula', models.CharField(max_length=13)),
            ],
        ),
    ]
