# Generated by Django 2.2.7 on 2023-02-07 02:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cardauth',
            fields=[
                ('id_cardauth', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=20)),
                ('auth', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('precio_total', models.FloatField(default=0)),
                ('tiene_combo', models.BooleanField(default=False)),
                ('tiene_oferta', models.BooleanField(default=False)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('cantidad_despachada', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now)),
                ('fecha_fin', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=100)),
                ('telefono', models.CharField(default='NONE', max_length=100)),
                ('direccion', models.CharField(default='NONE', max_length=100)),
                ('fecha_Nac', models.DateField(default=datetime.datetime.now)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(default='A', max_length=1)),
                ('tipo', models.CharField(default='M', max_length=1)),
                ('precio', models.FloatField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id_combo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('precio_total', models.FloatField()),
                ('estado', models.CharField(default='A', max_length=100)),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad_despachada', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('tipo', models.CharField(default='M', max_length=1)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=250)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('envio', models.FloatField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('razon_social', models.CharField(max_length=300)),
                ('ruc_cedula', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id_establecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('referencia', models.CharField(default='', max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('encargado', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('precioAntes', models.FloatField(default=0.0)),
                ('precio', models.FloatField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_entrega', models.CharField(default='Domicilio', max_length=100)),
                ('tipo_pago', models.CharField(default='Efectivo', max_length=100)),
                ('subtotal', models.FloatField()),
                ('envio', models.FloatField()),
                ('iva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
                ('observacion', models.CharField(max_length=400)),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Recibido', 'Recibido'), ('Proceso', 'Proceso'), ('Devuelto', 'Devuelto'), ('Anulado', 'Anulado')], default='Recibido', max_length=10)),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.DireccionEntrega')),
                ('establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id_premio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('estado', models.CharField(default='A', max_length=1)),
                ('stock_disponible', models.IntegerField()),
                ('puntos', models.IntegerField(default=0)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id_publicidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('tipo', models.CharField(choices=[('Superior', 'Superior'), ('Inferior', 'Inferior')], default='Superior', max_length=100)),
                ('url', models.CharField(max_length=100, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id_puntos', models.AutoField(primary_key=True, serialize=False)),
                ('dolarAPuntos', models.IntegerField(default=0)),
                ('puntosADolar', models.IntegerField(default=0)),
                ('puntosATarjeta', models.IntegerField(default=0)),
                ('tarjetaAPuntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=120)),
                ('token', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id_sorteo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('numGanadores', models.IntegerField(default=0)),
                ('maxGanadores', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Monto',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Producto',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(default='cliente', max_length=150)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=64)),
                ('foto', models.ImageField(default=' ', upload_to='')),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_unico', models.CharField(max_length=100, null=True)),
                ('token', models.CharField(default='0000', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaEnvio',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=3000)),
                ('envio', models.FloatField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionPedido',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('transaccion', models.CharField(max_length=100)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Producto_Producto',
            fields=[
                ('id_tarjetaxproducto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Producto_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Producto_Cliente',
            fields=[
                ('id_tarjetaxcliente', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fecha', models.DateTimeField(null=True)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Monto_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Monto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Monto_Cliente',
            fields=[
                ('id_tarjetaxcliente', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fecha', models.DateTimeField(null=True)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Monto')),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo_Usuario',
            fields=[
                ('id_sorteoxusuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_sorteo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Sorteo')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor_Pedido',
            fields=[
                ('id_repedido', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
                ('id_repartidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id_red', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('enlace', models.CharField(max_length=400)),
                ('icono', models.ImageField(upload_to='')),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=500)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Premios_Cliente',
            fields=[
                ('id_premioXcliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_canje', models.DateField()),
                ('fecha_entrega', models.DateField(null=True)),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Recibido', 'Recibido')], default='Recibido', max_length=10)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_premio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Premios')),
            ],
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id_politica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('detalle', models.TextField()),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Oferta')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(default='NOT', max_length=500)),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=100)),
                ('hora_inicio', models.CharField(max_length=100)),
                ('hora_fin', models.CharField(max_length=100)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento_ZonaEnvio',
            fields=[
                ('id_estabxzona', models.AutoField(primary_key=True, serialize=False)),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
                ('id_zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.ZonaEnvio')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento_Producto',
            fields=[
                ('id_estabxprod', models.AutoField(primary_key=True, serialize=False)),
                ('stock_disponible', models.IntegerField()),
                ('stock_despacho', models.IntegerField()),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(default='administrador', max_length=150)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Carrito',
            fields=[
                ('id_detallexcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cupones_Producto',
            fields=[
                ('id_cuponesproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('id_cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cupones')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cupones_Monto',
            fields=[
                ('id_cuponesmonto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('id_cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cupones')),
            ],
        ),
        migrations.CreateModel(
            name='Cupones_Cliente',
            fields=[
                ('id_cuponxcliente', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cupones')),
            ],
        ),
        migrations.AddField(
            model_name='cupones',
            name='id_establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento'),
        ),
        migrations.CreateModel(
            name='Cupon_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cupones')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Combo_Producto',
            fields=[
                ('id_comboxproducto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Combo')),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Combo_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Combo')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='id_establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento'),
        ),
        migrations.CreateModel(
            name='Codigo_Producto',
            fields=[
                ('id_codigoproducto', models.AutoField(primary_key=True, serialize=False)),
                ('codigoproducto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('id_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Codigo')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Codigo_Monto',
            fields=[
                ('id_codigomonto', models.AutoField(primary_key=True, serialize=False)),
                ('codigomonto', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('id_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Codigo_Cliente',
            fields=[
                ('id_codxcliente', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Codigo')),
            ],
        ),
        migrations.AddField(
            model_name='codigo',
            name='id_cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cupones'),
        ),
        migrations.AddField(
            model_name='codigo',
            name='id_establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento'),
        ),
        migrations.AddField(
            model_name='codigo',
            name='id_tarjetamonto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Monto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento'),
        ),
        migrations.CreateModel(
            name='Carrito_Tarjeta_Producto',
            fields=[
                ('id_carritoxtarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(default=0)),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_Tarjeta_Monto',
            fields=[
                ('id_carritoxtarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(default=0)),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Monto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_Oferta',
            fields=[
                ('id_carritoxoferta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_Cupones',
            fields=[
                ('id_carritoxcupones', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cupones')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_Combo',
            fields=[
                ('id_carritoxcombo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Combo')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente'),
        ),
        migrations.CreateModel(
            name='CanalUsuario',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanalMensaje',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('check_leido', models.BooleanField()),
                ('esAdmin', models.BooleanField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='canal',
            name='usuario_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Empleado'),
        ),
        migrations.AddField(
            model_name='canal',
            name='usuario_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Cliente'),
        ),
        migrations.CreateModel(
            name='CalificacionPedido',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(default=5)),
                ('justificacion', models.CharField(max_length=500)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
    ]
