# Generated by Django 3.0.10 on 2020-09-20 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20200828_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='NULL', max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=64)),
                ('fecha_R', models.DateField(default=datetime.datetime.now)),
                ('tipo_usuario', models.CharField(default='cliente', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=100)),
                ('telefono', models.CharField(default='NONE', max_length=100)),
                ('direccion', models.CharField(default='NONE', max_length=100)),
                ('fecha_Nac', models.DateField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario')),
            ],
        ),
    ]
