# Generated by Django 2.2.7 on 2022-09-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0073_repartidor_repartidor_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonaenvio',
            name='zona',
            field=models.CharField(max_length=3000),
        ),
    ]
