# Generated by Django 2.2.7 on 2022-09-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0075_auto_20220927_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta_monto_cliente',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
