# Generated by Django 2.2.7 on 2022-10-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0079_carrito_tarjeta_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta_Monto_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
                ('tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Monto')),
            ],
        ),
    ]
