# Generated by Django 2.2.7 on 2022-10-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0080_tarjeta_monto_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='id_tarjetamonto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Monto'),
        ),
    ]
