# Generated by Django 2.2.7 on 2022-10-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0081_codigo_id_tarjetamonto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Recibido', 'Recibido'), ('Espera', 'Espera'), ('Devuelto', 'Devuelto'), ('Anulado', 'Anulado')], default='Recibido', max_length=10),
        ),
    ]
