# Generated by Django 2.2.7 on 2022-10-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0082_auto_20221008_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Recibido', 'Recibido'), ('EnProceso', 'EnProceso'), ('Devuelto', 'Devuelto'), ('Anulado', 'Anulado')], default='Recibido', max_length=10),
        ),
    ]
