# Generated by Django 2.2.7 on 2022-10-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0084_auto_20221008_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='tarjeta_producto',
            name='id_producto',
        ),
        migrations.CreateModel(
            name='Tarjeta_Producto_Producto',
            fields=[
                ('id_tarjetaxproducto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Producto')),
            ],
        ),
    ]
