# Generated by Django 2.2.7 on 2022-11-13 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0086_carrito_tarjeta_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta_monto_pedido',
            old_name='pedido',
            new_name='id_pedido',
        ),
        migrations.RenameField(
            model_name='tarjeta_monto_pedido',
            old_name='tarjeta',
            new_name='id_tarjeta',
        ),
        migrations.AddField(
            model_name='tarjeta_monto',
            name='id_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido'),
        ),
        migrations.AddField(
            model_name='tarjeta_producto',
            name='id_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido'),
        ),
        migrations.CreateModel(
            name='Tarjeta_Producto_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Producto')),
            ],
        ),
    ]
