# Generated by Django 2.2.7 on 2022-11-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0087_auto_20221112_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fecha_fin',
            field=models.DateField(default=1998),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateField(default=1997),
            preserve_default=False,
        ),
    ]
