# Generated by Django 2.2.7 on 2022-11-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0088_auto_20221114_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_unico',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
