# Generated by Django 2.2.7 on 2023-01-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0091_auto_20221214_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(default='0000', max_length=500),
        ),
    ]
