# Generated by Django 2.2.7 on 2023-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0092_usuario_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id_publicidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('tipo', models.CharField(choices=[('Superior', 'Superior'), ('Inferior', 'Inferior')], default='Superior', max_length=100)),
            ],
        ),
    ]
