# Generated by Django 2.2.7 on 2023-01-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0093_publicidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
