# Generated by Django 2.2.7 on 2023-01-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0094_auto_20230118_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id_puntos', models.AutoField(primary_key=True, serialize=False)),
                ('dolarAPuntos', models.IntegerField(default=0)),
                ('puntosADolar', models.IntegerField(default=0)),
            ],
        ),
    ]
