# Generated by Django 2.2.7 on 2023-01-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0095_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
