# Generated by Django 2.2.7 on 2023-01-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0096_publicidad_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='fecha_fin',
            field=models.DateField(default='2023-02-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicidad',
            name='fecha_inicio',
            field=models.DateField(default='2023-02-20'),
            preserve_default=False,
        ),
    ]
