# Generated by Django 2.2.7 on 2023-01-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0099_remove_usuario_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntos',
            name='puntosATarjeta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puntos',
            name='tarjetaAPuntos',
            field=models.IntegerField(default=0),
        ),
    ]
