# Generated by Django 2.2.7 on 2023-01-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0101_premios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premios_Cliente',
            fields=[
                ('id_premioXcliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_premio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Premios')),
            ],
        ),
    ]
