# Generated by Django 2.2.7 on 2023-01-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0102_premios_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premios_cliente',
            old_name='fecha_inicio',
            new_name='fecha_canje',
        ),
        migrations.RenameField(
            model_name='premios_cliente',
            old_name='fecha_fin',
            new_name='fecha_entrega',
        ),
    ]
