# Generated by Django 2.2.7 on 2023-01-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0103_auto_20230127_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='premios_cliente',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Recibido', 'Recibido')], default='Recibido', max_length=10),
        ),
    ]
