# Generated by Django 2.2.7 on 2023-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0104_premios_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
