# Generated by Django 2.2.7 on 2023-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0105_pedido_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ban',
            field=models.IntegerField(default=0),
        ),
    ]
