# Generated by Django 2.2.7 on 2023-03-05 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0108_auto_20230217_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mesTarjetas',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numTarjetas',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
