# Generated by Django 2.2.7 on 2023-02-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0108_auto_20230208_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalmensaje',
            name='usuario_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Cliente'),
        ),
    ]
