# Generated by Django 2.2.7 on 2023-02-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0109_auto_20230208_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanalUsuario',
        ),
    ]
