# Generated by Django 2.2.7 on 2023-03-05 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0109_auto_20230305_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mesTarjetas',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
