# Generated by Django 2.2.7 on 2023-03-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0110_auto_20230305_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='mesTarjetas',
        ),
    ]
