# Generated by Django 2.2.7 on 2023-03-05 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0111_remove_cliente_mestarjetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mesTarjetas',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
