# Generated by Django 2.2.7 on 2023-03-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0112_cliente_mestarjetas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='mesTarjetas',
            new_name='monthCard',
        ),
    ]
