# Generated by Django 2.2.7 on 2023-03-05 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0113_auto_20230305_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='monthCard',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
