# Generated by Django 2.2.7 on 2023-03-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0115_backup_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='version',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
