# Generated by Django 2.2.7 on 2023-10-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0116_cliente_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numValidacion',
            field=models.FloatField(default=0, null=True),
        ),
    ]
