# Generated by Django 2.2.7 on 2023-11-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0117_cliente_numvalidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardauth',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
