# Generated by Django 2.2.7 on 2023-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0118_cardauth_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardauth',
            name='numValidacion',
            field=models.FloatField(default=0, null=True),
        ),
    ]
